### ISSUE TITLE
Wrong display when applying filter_multi_select.css 

### ISSUE THREAD

**Issue by smartlegionlab** [andreww1011/filter-multi-select#10]
Hello. I really liked your implementation, but I can't apply the styles correctly. No matter what I do, everything is displayed incorrectly! Tell me what could be the problem?

**Comment by smartlegionlab** [comment]
As I understand it, I'm using Bootstrap 3, so it doesn't display correctly. Can I somehow use with Bootstrap 3?

**Comment by andreww1011** [comment]
Try adding the following styles after bootstrap v3 has been linked in your html source:

<pre><code><style>
	:root{--primary: #007bff;}
	[tabindex="-1"]:focus {outline: 0 !important;}
	.custom-control-input:focus~.custom-control-label::before {box-shadow: 0 0 0 1px #fff, 0 0 0 .2rem rgba(0, 123, 255, .25)}
	html {font-size: 1rem}
	[hidden] {display: none !important;}
</style></code></pre>

See the example file in the attached zip.  Download this file in the /dist directory to run.
[example_bs3.html.zip](https://github.com/andreww1011/filter-multi-select/files/8250456/example_bs3.html.zip)

**Comment by smartlegionlab** [comment]
Thank you very much! Everything worked! I wish the development of your project.
