### ISSUE TITLE
How to get label inline & language support

### ISSUE THREAD

**Issue by skyynet** [andreww1011/filter-multi-select#12]
Great plugin. I would like to have the label of the select field not left of it, but inside the select.
Is there an elegant way to do this?
![example](https://user-images.githubusercontent.com/1677968/170791184-3b3e4d07-3ff7-432d-b141-688f1e105ed7.png)

I could move the label by applying `position:relative; left:80px; z-index:99;` to it.
As the labels have different widths, I would have to do this manually for each select field.
Of course, the "nothing selected" placeholder and the selected options would have to move to the right, too.
I couldn't figure out how to move this.

As my website is available in three different languages, it would also be great, if the few text strings could be  shown in the correct language. I just saw "nothing selected" and "Select All" directly in the JS. Of course, I could duplicate the JS and replace the strings, but that's not really elegant.

**Comment by andreww1011** [comment]
Please see v1.3.0 for inline label support.

Regarding language support, you can customize the text of the label, placeholder, filter, and select all checkbox upon initialization using JS.  See the readme and example html file.

**Comment by skyynet** [comment]
Wow, you really rock, Andrew. Thanks. Now I can improve a huge form on my homepage to your class. When I'm finished and it's online, I'll drop a note.
