### ISSUE TITLE
Enahncement Request: Option to display only x options with +n for huge option lists

### ISSUE THREAD

**Issue by skyynet** [andreww1011/filter-multi-select#14]
While everything works great for small option lists, the layout will break for huge ones.
I have a multi selector for >200 cellphone brands. Even with 4 entries, it will break the layout

![grafik](https://user-images.githubusercontent.com/1677968/172848207-bc424d22-6b8d-4ba3-a83d-14deda67dd0e.png)

It would be great to have an option to show only x entries and if more are selected, e.g. for x=1 show n1 n2 n3 +33.

**Comment by andreww1011** [comment]
I would handle that with CSS.  Try adding the following:
<pre><code>.filter-multi-select { 
	counter-reset: nitems;
}

.filter-multi-select > .viewbar > .selected-items > .item:nth-child(n+4) {
	counter-increment: nitems;
	visibility: hidden;
	width: 0;	
	padding: 0;
	border: 0;
	margin: 0;
}

.filter-multi-select > .viewbar > .selected-items > .item:nth-child(3) ~ .item:last-child::before {
	position: absolute;
 	visibility: visible;
	content: "+" counter(nitems);
	color: black;
}</code></pre>

**Comment by skyynet** [comment]
Wow. I didn't know this was possible with CSS. Works great as intended.

Would it be possible to limit the number of items according to their actual lengths?

e.g. for ABB AEG AGM Amplicomms GeneralDynamics
show ABB AEG AGM +2
but   GeneralDynamics +4

Otherwise, I would have to limit the number of shown entries by the length of the longest entry.

Why don't you add a "Sponsor me" button? I really appreciate your plugin and would like to show this.

**Comment by andreww1011** [comment]
I would still try to handle that with css.  There's no way in css (that I know of) to dynamically change the limit based on the lengths.  The following css sticks the number of hidden entries to the right.  There's still the case where items may be clipped if they are really long, but hopefully you can work that out.

<pre><code>.filter-multi-select { 
	counter-reset: nitems;
}

.filter-multi-select > .viewbar > .selected-items > .item:nth-child(n+4) {
	counter-increment: nitems;
	visibility: hidden;
	width: 0;	
	padding: 0;
	border: 0;
	margin: 0;
}

.filter-multi-select > .viewbar > .selected-items > .item:nth-child(3) ~ .item:last-child::before {
	visibility: visible;
	content: "+" counter(nitems);
	color: black;
}

.filter-multi-select > .viewbar {
	white-space: nowrap;
	overflow: hidden;
}

.filter-multi-select > .viewbar > .selected-items {
	width: inherit;
	display: inline-block;
}

.filter-multi-select > .viewbar > .selected-items > .item:nth-child(3) ~ .item:last-child {
	position: sticky;
	right: 0.75rem;
	z-index: 100;
}
 
 .filter-multi-select > .viewbar::after {
	visibility: visible;
	background: linear-gradient(to right, rgba(255, 255, 255, 0), rgba(255, 255, 255, 0.70) 40%, white 70%);
	content: "";
	position: absolute;
	right: 0;
	width: 100px;
	height: 100%;
	box-sizing: border-box;
	top: 0;
	padding: 0.375rem 1px;
	background-clip: content-box;
	pointer-events: none;
}</code></pre>

**Comment by skyynet** [comment]
Unfortunately this doesn't work for me:

![grafik](https://user-images.githubusercontent.com/1677968/173883511-a4607dc0-0f87-4353-9a08-30958e5859c4.png)

instead of the version before with child(n+2) 

![grafik](https://user-images.githubusercontent.com/1677968/173883829-32fad42c-7723-43ce-906b-1188b688657c.png)

I think, I just stick with the old one. Works and looks ok.

![grafik](https://user-images.githubusercontent.com/1677968/173883697-13506953-9790-417e-825f-73b446b85f2d.png)
