### ISSUE TITLE
append not working correctly

### ISSUE THREAD

**Issue by AliTakrar** [andreww1011/filter-multi-select#9]
when i append new options to multiselect its append out of it and its shown in out of dropdown item, i need this for cascading dropdown and multiselect is in the last stage ، and it should populate with ajax and append

**Comment by andreww1011** [comment]
Hi Ali-

I'm sorry, I do not understand.  Can you please clarify?  Can you write sample code of what you are trying to do?

Best,
-Andrew

**Comment by AliTakrar** [comment]
I solved this problem in another way
